# Generated by Django 4.2.3 on 2023-07-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slotBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
